config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'

  resources :units, :tenants


  # rails API
  namespace :api do
    namespace :v1, constraints: { format: 'json' } do
      resources :tenants
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :units
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  belongs_to :unit
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :building
  has_many :tenants
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  #before_action :authenticate_user!
  #after_action :verify_authorized
  skip_before_filter :verify_authenticity_token
end

app/controllers/api/v1/tenants_controller.rb
class Api::V1::TenantsController < Api::V1::BaseController
  def index
    render json: Tenant.all.map{ |t| { id: t.id, name: t.name, description: t.description } }
  end

  def create
    tenant = Tenant.create(name: params[:name], description: params[:description])
    render json: { id: tenant.id, name: tenant.name, description: tenant.description }
  end

  def destroy
    Tenant.find(params[:id]).destroy

    render json: { success: 1 }
  end

  def update
    tenant = Tenant.find(params[:id])

    tenant.name = params[:tenant][:name]
    tenant.description = params[:tenant][:description]

    if tenant.save!
      render json: { success: 1 }
    else
      render json: { success: 0 }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def new
    @unit = Unit.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Sunrise
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    /= javascript_include_tag 'http://cdn.jsdelivr.net/vue/1.0.19/vue.min.js'
    = javascript_include_tag 'http://cdn.jsdelivr.net/vue/1.0.19/vue.js'
    = javascript_include_tag 'https://cdn.jsdelivr.net/vue.resource/0.7.0/vue-resource.min.js'
    = csrf_meta_tags

  body
    p

    .ui.main.container
      .ui.menu
        .header.item
          h2= link_to 'Sunrise App', '/'
        a.item Rent
        = link_to 'Units', units_path, class: 'item'
        = link_to 'Tenants', tenants_path, class: 'item'
        a.item Reports
        .right.menu
          .item
            .ui.icon.input
              input(type="text" placeholder="Search...")
              i.search.link.icon
          a.ui.item Logout
      = yield

app/views/pages/welcome.html.slim
h2 Welcome Page

app/views/tenants/index.html.slim
h2 Tenants

template#tenant-row
  tr
    td v-on:dblclick="editTenant(tenant)"
      span v-if="editMode === false"
        |{{ tenant.name }}
      input type="text" v-model="tenant.name" v-if="editMode"
    td v-on:dblclick="editTenant(tenant)"
      span v-if="editMode === false"
        |{{ tenant.description }}
      input type="text" v-model="tenant.description" v-if="editMode"
    td
      span v-if="editMode === false"
        = link_to 'Delete', '/', class: [:ui, :button, :small, :right, :floated, :red], 'v-on:click.prevent': 'removeTenant(tenant)'
        = link_to 'Edit', '/', class: [:ui, :button, :small, :right, :floated], 'v-on:click.prevent': 'editTenant(tenant)'
      span(v-else)
        = link_to 'Save', '/', class: [:ui, :button, :small, :right, :floated, :green], 'v-on:click.prevent': 'updateTenant(tenant)'
        = link_to 'Cancel', '/', class: [:ui, :button, :small, :right, :floated], 'v-on:click.prevent': 'cancelEdit(tenant)'

#verify-delete.ui.modal.small
  .content
    p
      'Really delete tenant
      span#tenant-name
      '?
  .actions
    .ui.cancel.button
      'No
    .ui.approve.green.right.labeled.icon.button
      'Yes
      i.checkmark.icon

form.ui.form
  table.ui.celled.table
    thead
      tr
        th Name
        th Description
        th Unit
    tbody
      tr is="tenant-row" v-for="tenant in tenants" :tenant="tenant"
      tr
        td
          input type="text" placeholder="name" v-model="new_name"
        td
          input type="text" placeholder="description" v-model="new_description"
        td
          = select_tag('county_tax[state]',
            options_for_select([['4', '4'], ['5', '5'], ['6', '6']]),
            prompt: 'select unit...',
            class: 'ui dropdown',
            'v-model': 'new_unit')
          = link_to 'Add Tenant', '/', class: [:ui, :button, :right, :floated], 'v-on:click.prevent': 'addTenant'

javascript:
  $(document).ready(function() {
    Vue.component('tenant-row', {
      template: '#tenant-row',
      props: ['tenant'],
      data: function() {
        return {
          editMode: false,
          prev_name: '',
          prev_description: ''
        }
      },
      methods: {
        removeTenant: function(tenant) {
          var self = this;
          $('#tenant-name').text(tenant.name);

          $('#verify-delete').modal({
            onApprove: function() {
              var tenantsEndpoint = self.$resource('api/v1/tenants{/id}');
              // delete item
              tenantsEndpoint.delete({id: tenant.id}).then(function (response) {
                // success callback
                self.$parent.$data['tenants'].$remove(tenant);
              }, function (response) {
                // error callback
                console.log("error: " + response)
              });
            }
          }).modal('show');
        },
        editTenant: function(tenant) {
          this.editMode = true;
          this.prev_name = tenant.name;
          this.prev_description = tenant.description;
        },
        cancelEdit: function(tenant) {
          this.editMode = false;
          tenant.name = this.prev_name;
          tenant.description = this.prev_description;
        },
        updateTenant: function(tenant) {
          this.editMode = false;
          var self = this;

          var tenantsEndpoint = this.$resource('api/v1/tenants{/id}');
          // update item
          var updated_params = { name: tenant.name, description: tenant.description };
          tenantsEndpoint.update({id: tenant.id}, { tenant: updated_params }).then(function (response) {
            // success callback
          }, function (response) {
            // error callback
            console.log("error: " + response)
          });
        }
      }
    })

    var vm = new Vue({
      el: 'body',
      ready: function() {
        var tenantsEndpoint = this.$resource('api/v1/tenants{/id}');

        // get item
        tenantsEndpoint.get({}).then(function (response) {
          this.$set('tenants', response.data);
        });
      },
      data: {
        tenants: [],
        new_name: '',
        new_description: ''
      },
      methods: {
        addTenant: function() {
          var newTenant = { name: this.new_name, description: this.new_description };
          var tenantsEndpoint = this.$resource('api/v1/tenants{/id}');

          tenantsEndpoint.save(newTenant).then(function (response) {
            // success callback
            this.$data.tenants.push(response.data);
          }, function (response) {
            // error callback
            console.log("error: " + response)
          });
          // clear fields
          this.new_name = '';
          this.new_description = '';
        }
      }
    })

    $('select.dropdown').dropdown();
  });

app/views/units/index.html.slim
<h2>Units</h2>

#units
  /p
    |{{ units | json }}

  form.ui.form
    table.ui.celled.table
      thead
        tr
          th Number
          th Tenant
          th Rate
          th Type
      tbody
        tr(v-for="unit in units")
          td
            |{{ unit.number }}
          td
            |{{ unit.tenant }}
          td
            |{{ unit.rate }}
          td
            |{{ unit.type }}
        tr
          td
            input type="text" placeholder="number" v-model="new_number"
          td
            input type="text" placeholder="tenant" v-model="new_tenant"
          td
            input type="text" placeholder="rate" v-model="new_rate"
          td
            input type="text" placeholder="type" v-model="new_type" v-on:keyup.enter="submit"


javascript:
  $(document).ready(function() {
    var vm = new Vue({
      el: '#units',
      data: {
        units: [
          { number: '1', rate: 1200, type: '2bd', tenant: 'John Lee' },
          { number: '2', rate: 1100, type: '2bd', tenant: 'Lisa Smith' },
          { number: '3', rate: 900, type: '1bd', tenant: 'Mark M.' }
        ],
        new_number: '',
        new_receipt: '',
        new_tenant: '',
        new_rate: '',
        new_type: ''
      },
      methods: {
        submit: function() {
          var new_unit = {
                           number: this.new_number,
                           receipt: this.new_receipt,
                           rate: this.new_rate,
                           type: this.new_type,
                           tenant: this.new_tenant
                         }
          this.$data.units.push(new_unit);

          new_number = '';
          new_receipt = '';
          new_tenant = '';
          new_rate = '';
          new_type = '';
        }
      }
    });
  });

app/views/units/new.html.slim
h2 Add New Unit

= simple_form_for @unit, html: { class: 'ui form' }  do |f|
  .fields
    .five.wide.field
      = f.input :number
    .eleven.wide.field
      = f.input :description
  = f.button :submit, 'Save', class: 'ui button'